#!/usr/bin/env python3
"""Generate `cache-list.js`, the icon set the service worker warms in the background.

Why this exists: the games load their menu art the moment a page opens, which on a
very first visit happens *before* the service worker controls the page — so those
files never reach the cache and the home screen renders broken the first time the
child opens the app offline.

Precaching them at install would be wrong too: it is ~8.6 MB, and blocking
installation on it makes adding the app to a home screen feel broken. So the
worker warms them in the background once, after it activates.

The list is generated rather than hand-written because it is long and would rot
silently. Re-run after adding, renaming or removing icon art, and commit the
result:

    python tools/build-cache-list.py

Backgrounds are deliberately excluded — they are cached on demand as each game is
actually played.

This reads the generated `assets-runtime/` WebP tree, not the `assets/` masters:
the runtime tree is what the pages actually reference. Re-run
`tools/build-runtime-assets.py` first if art changed, or this list will name files
that do not exist yet.
"""

from __future__ import annotations

import pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
# Magic Spelling joined on 2026-08-27 with the ABC head. This list is HAND-KEPT, so a
# new theme directory is built by build-runtime-assets.py (which walks the tree) and
# then silently left out of the offline cache unless it is added here -- the app works
# online and shows a blank robot on an iPad in aeroplane mode.
ICON_DIRS = ["assets-runtime/space/icons", "assets-runtime/unicorn/icons",
             "assets-runtime/spelling/icons"]
# Referenced by menus or mascots. `bg-nebula.webp` is the one background included:
# it is the menu's own backdrop, and the menu is the screen every session opens on,
# so leaving it out is the difference between the app looking finished offline and
# looking half-loaded. The per-game backgrounds stay on demand.
EXTRA = [
    "assets-runtime/unicorn/princess.webp",
    "assets-runtime/unicorn/unicorn-fixed.webp",
    "assets-runtime/space/bg-nebula.webp",
]
OUT = HERE / "cache-list.js"


def main() -> None:
    paths: list[str] = []
    for d in ICON_DIRS:
        directory = HERE / d
        if not directory.is_dir():
            raise SystemExit(f"missing icon directory: {d}")
        paths += sorted(f"./{d}/{p.name}" for p in directory.iterdir() if p.suffix.lower() == ".webp")
    paths += [f"./{p}" for p in EXTRA if (HERE / p).exists()]

    total = sum((HERE / p[2:]).stat().st_size for p in paths)
    body = ",\n  ".join(f'"{p}"' for p in paths)
    OUT.write_text(
        "/* Generated by tools/build-cache-list.py — do not edit by hand.\n"
        f"   {len(paths)} menu/mascot images, {total / 1024:.0f} KB, warmed in the\n"
        "   background after the service worker activates. Re-run the generator\n"
        "   after changing icon art. */\n"
        f"self.__WARM_IMAGES = [\n  {body}\n];\n",
        encoding="utf-8",
    )
    print(f"  {len(paths)} files, {total / 1024:.0f} KB -> cache-list.js")


if __name__ == "__main__":
    main()
